version: "3.8"
services:
  htmltopdf:
    image: htmltopdf:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: htmltopdf
    volumes: # host:container
      - "./logs:/app/logs:rw"
    ports:
      - "5000:5000"
